import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Nav />
        {children}
      </body>
    </html>
  );
}

function Nav() {
  return (
    <nav className="flex justify-between">
      <div>
        <h1>Cutter</h1>
        <p>Twitter but cute</p>
      </div>
      <Link href="/">Home</Link>
      <Link href="/trend">Trending</Link>
    </nav>
  );
}
